version: "3.9"

services:
  app:
    image: golang
    environment:
      - PROJECT_ROOT_DIR=/workspace
    volumes:
      - .:/workspace
      - go-data:/go
    working_dir: /workspace
volumes:
  go-data:
